[env]
TOOL_VERSION_BUNDLER_AUDIT="0.6.1"

[tasks.pre-build-bundler-audit-docker]
command = "cp"
args = ["../../../bin/data-forwarder", "data-forwarder"]

[tasks.post-build-bundler-audit-docker]
command = "rm"
args = ["data-forwarder"]

[tasks.build-bundler-audit-docker]
dependencies = ["build-bundler-audit-docker-tag-version", "build-bundler-audit-docker-tag-latest"]

[tasks.build-bundler-audit-docker-tag-version]
command = "docker"
args = ["build", "-t", "kiln/bundler-audit:${TOOL_VERSION_BUNDLER_AUDIT}", "--build-arg", "BUNDLER_AUDIT_VERSION=${TOOL_VERSION_BUNDLER_AUDIT}", "."]

[tasks.build-bundler-audit-docker-tag-latest]
command = "docker"
args = ["tag", "kiln/bundler-audit:${TOOL_VERSION_BUNDLER_AUDIT}", "kiln/bundler-audit:latest"]

